### PR TITLE
Use RT::Transaction instead of outdated fork

### PR DESCRIPTION
**Pull request by btb**
RTx::AssetTracker::Transaction was forked from RT::Transaction, but since Asset transactions are really just generic RT transactions, we can use RT::Transaction with just a few addons. This lets us throw away a lot of outdated code and further modernized the display elements.

### CODE REVIEW

**Comment by btb** [comment]
Thanks Todd, I know these are some fairly sizeable changes

**Comment by JvdW** [comment]
There is a problem with this commit. If you add an asset WITHOUT filling in any customfields it will add the asset, if you fill in ONE of the customfields it will not add the asset but spit out the following error in the logs:
[Thu Feb 28 07:57:52 2013] [error]: RTx::AssetTracker::Asset::Queue Unimplemented in RT::Record. (/opt/rt4test/sbin/../lib/RT/Record.pm line 1600) 

Stack:
  [/usr/share/perl5/DBIx/SearchBuilder/Record.pm:494]
  [/opt/rt4test/sbin/../lib/RT/Record.pm:1600]
  [/opt/rt4test/sbin/../lib/RT/Record.pm:1575]
  [/opt/rt4test/sbin/../lib/RT/Record.pm:1650]
  [/opt/rt4test/sbin/../lib/RT/Transaction.pm:1174]
  [/opt/rt4test/local/plugins/RTx-AssetTracker/lib/RTx/AssetTracker/Asset_Overlay.pm:441]
  [/opt/rt4test/local/plugins/RTx-AssetTracker/lib/RTx/AssetTracker/Interface/Web.pm:536]
  [/opt/rt4test/local/plugins/RTx-AssetTracker/html/AssetTracker/Asset/ModifyAll.html:104]
  [/opt/rt4test/sbin/../lib/RT/Interface/Web.pm:634]
  [/opt/rt4test/sbin/../lib/RT/Interface/Web.pm:335]
  [/opt/rt4test/share/html/autohandler:53](/opt/rt4test/sbin/../lib/RT/Interface/Web/Handler.pm:208)
[Thu Feb 28 07:57:52 2013] [critical]: Transaction not committed. Usually indicates a software fault.Data loss may have occurred (/opt/rt4test/sbin/../lib/RT/Interface/Web/Handler.pm:167)

**Comment by plabbett** [comment]
I can attest to the above comment, using RT 4.0.10

[Fri Mar  8 14:36:45 2013] [error]: RTx::AssetTracker::Asset::Queue Unimplemented in RT::Record. (/opt/rt4/sbin/../lib/RT/Record.pm line 1600)

Stack:
  [/usr/local/share/perl5/DBIx/SearchBuilder/Record.pm:494]
  [/opt/rt4/sbin/../lib/RT/Record.pm:1600]
  [/opt/rt4/sbin/../lib/RT/Record.pm:1575]
  [/opt/rt4/sbin/../lib/RT/Record.pm:1655]
  [/opt/rt4/sbin/../lib/RT/Transaction.pm:1172]
  [/opt/rt4/local/plugins/RTx-AssetTracker/lib/RTx/AssetTracker/Asset_Overlay.pm:441]
  [/opt/rt4/local/plugins/RTx-AssetTracker/lib/RTx/AssetTracker/Interface/Web.pm:536]
  [/opt/rt4/local/plugins/RTx-AssetTracker/html/AssetTracker/Asset/ModifyAll.html:104]
  [/opt/rt4/sbin/../lib/RT/Interface/Web.pm:634]
  [/opt/rt4/sbin/../lib/RT/Interface/Web.pm:335]
  [/opt/rt4/share/html/autohandler:53](/opt/rt4/sbin/../lib/RT/Interface/Web/Handler.pm:208)
[Fri Mar  8 14:36:45 2013] [critical]: Transaction not committed. Usually indicates a software fault.Data loss may have occurred (/opt/rt4/sbin/../lib/RT/Interface/Web/Handler.pm:167)

**Comment by plabbett** [comment]
I was able to resolve this by applying the 2.0.0b2 tag, re-installing RTx-AssetTracker, and then applying https://github.com/cognusion/rt-extension-assettracker/commit/ef64236b36bf08f31921ed9f7c1fc735a68e9598

**Comment by btb** [comment]
fixed with https://github.com/chakatodd/rt-extension-assettracker/issues/45

**Comment by plabbett** [comment]
https://github.com/chakatodd/rt-extension-assettracker/pull/45 confirmed to resolve my issue.

**Pull request merged**
